spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.macacolabs.site:5050/insilence
    username: team4
    password: team4

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: "Ar9UALWCe0Mwd1N1TSQvi16xppnDPmzeiqKEJChMR6d33hd0uydctmPRy7pBaE6OMbMzs2hL7T0E4UZcaMXsBQ=="
  expiration: 1800000
  refresh-expiration : 604800000